server:
  port: 8002
#  servlet:
#    context-path: /content-service
spring:
  application:
    name: content-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    top.kjwang.share.content.mapper: debug
date:
  format: "yyyy-MM-dd HH:mm:ss"

#show: true
rocketmq:
  name-server: 47.98.246.199:9876
  producer:
    # 必须指定 group
    group: test-group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
    customized-trace-topic: TEST__TOPIC