GET http://localhost:8000/content-service/share/notice
Accept: application/json

###

GET http://localhost:8000/content-service/share/list
Accept: application/json
###

GET http://localhost:8000/content-service/share/list?title=并发编程
Accept: application/json
###

GET http://localhost:8000/content-service/share/list?pageNo=3&pageSize=2
Accept: application/json
token: {{token}}
###

GET http://localhost:8000/content-service/share/1
Accept: application/json
token: {{token}}
###

POST http://localhost:8000/content-service/share/exchange
content-type: application/json
Accept: application/json
token: {{token}}

{
  "userId": 2,
  "shareId": 3
}

###
POST http://localhost:8000/content-service/share/contribute
content-type: application/json
Accept: application/json
token: {{token}}

{
  "userId": 1,
  "author": "尤雨溪",
  "title": "详解 Vue.js",
  "isOriginal": 1,
  "price": 20,
  "downloadUrl": "http://cn.vuejs.org",
  "cover": "https://niit-soft.oss-cn-hangzhou.aliyuncs.com/share-app/Vue.jpg",
  "summary": "详解 Vue.js 详解 Vue.js 详解 Vue.js 详解 Vue.js 详解 Vue.js"
}

###
GET http://localhost:8000/content-service/share/my-contribute?pageNo=2&pageSize=2
Accept: application/json
token: {{token}}
###