server:
  port: 8001
  servlet:
    context-path: /user-service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    top.kjwang.share.user.mapper: debug