server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
    gateway:
      discovery:
        locator:
          # 允许网关通过服务发现组件，找到其他的微服务
          enabled: true
      routes:
        - id: route-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: route-content
          uri: lb://content-service
          predicates:
            - Path=/content-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许请求来源
            allowedOriginPatterns: '*'
            # 允许携带的头信息
            allowedHeaders: '*'
            # 允许的请求方式
            allowedMethods: '*'
            # 是否允许携带 cookie
            allowCredentials: 'true'
            # 跨域检测的有效期，会发起一个OPTION请求
            maxAge: '3600'
date:
  format: "yyyy-MM-dd HH:mm:ss"

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    routes:
      - name: 用户route-user
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /user-service/v3/api-docs?group=user
        service-name: user-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /
        order: 2
      - name: 内容route-content
        url: /content-service/v3/api-docs?group=content
        service-name: content-service
        # 路由前缀
        context-path: /
        order: 3